### PR TITLE
luarocks: fix usage of local configs

### PR DESCRIPTION
**Pull request by oleg-jukovec**
Skipping of load local configuration files will result in problems and loss of backward compatibility.

Part of https://github.com/tarantool/tt/issues/1003

### CODE REVIEW

**Comment by oleg-jukovec** [comment]
PR with update in tt: https://github.com/tarantool/tt/pull/1004
PR with update in tt-ee: https://github.com/tarantool/tt-ee/pull/257

**Review by themilchenko — APPROVED** [review]
Looks good, thank you!

**Comment by oleg-jukovec** [comment]
It looks like tests are already broken by other commits. I suggest just to fix the issue here and do a proper rebase in #22 .

**Review by DerekBum — APPROVED** [review]

**Comment by oleg-jukovec** [comment]
It looks like there's too much work to do here. Let's just rebase to the latest version, see #24 .

**Pull request closed without merging**
