### PR TITLE
Update luarocks to 3.1.2

### PR DESCRIPTION
**Pull request by olegrok**

### CODE REVIEW

**Review by zwirec — DISMISSED** [review]

**Comment by rosik** [comment]
Why do you do this?

1. We've discussed it with @zwirec and decided there is nothing interesting between 3.1.1 (current base) and 3.1.2 (the one you are merging with). What's changed?
2. It's better to rebase on top of 3.1.2 instead of creating merge commits - they complicate diffs.

**Comment by olegrok** [comment]
> Why do you do this?
> 
> 1. We've discussed it with @zwirec and decided there is nothing interesting between 3.1.1 (current base) and 3.1.2 (the one you are merging with). What's changed?
> 2. It's better to rebase on top of 3.1.2 instead of creating merge commits - they complicate diffs.

1. To be closer to upstream
2. Rebase button is available on github, it does not create merge commits

**Comment by rosik** [comment]
1. So what? We will do it when it's reasonable.
2. It will rebase master on top of luarocks-3.x, please don't.

**Comment by olegrok** [comment]
> 1. So what? We will do it when it's reasonable.
> 2. It will rebase master on top of luarocks-3.x, please don't.

Ok, let's close it

**Pull request closed without merging**
